services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=project
      - GO_ENV=production
      - TZ=Asia/Jakarta
      - ENV=
    ports:
      - "10001:10001"
      - "8081:8081"
    depends_on:
      - db
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
  liquibase:
    build:
      context: .
      dockerfile: liquibase/Dockerfile
    depends_on:
      - db
  #    volumes:
  #      - ./liquibase/ticketing-system/sql:/liquibase/changelog
  db:
    image: mysql:8.0.23
    platform: linux/amd64
    volumes:
      - /var/data/mysql:/var/lib/mysql
      - /etc/mysql:/etc/mysql
      - ./mysql-files:/var/lib/mysql-files
    restart: always
    environment:
      MYSQL_DATABASE: 'project'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'project'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'MyPassword_123'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'MyPassword_123'
      ENV: 'stage'
    ports:
      - "3308:3306"
volumes:
  .:
  logvolume01: {}
